version: '2'
services:
  sonarqube:
    scale: 1
    health_check:
      port: 9000
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  db:
    scale: 1
